spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: api-cadastro-cuidador-funcionario
          uri: http://localhost:8081
          predicates:
            - Path=/api/funcionarios**
        - id: api-cadastro-pet
          uri: http://localhost:8080
          predicates:
            - Path=/pets/**
        - id: api-gerenciamento-reserva
          uri: http://localhost:8082
          predicates:
            - Path=/reservas/**

server:
  port: 8079

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG